feat: created view student page, intalled react-router-dom #16
SAMAHAN-Systems-Development/ACMS-frontend-2023 pull request #26
Opened 2024-01-18 13:46 UTC by shunindesuuu

di ko kabalo saon sa story huhu

2024-01-21 13:45 UTC, CyrilOlanolan approved these changes

2024-02-17 06:58 UTC, CyrilOlanolan requested changes
Remove react-router-dom

2024-02-17 06:58 UTC, CyrilOlanolan commented on src/components/student/StudentPage.tsx
> +import { useParams } from 'react-router-dom';
dont use react-router-dom because next has a built-in navigation library for this. may conflict with it too. check `useSearchParams`.

2024-02-27 16:25 UTC, closed without merging

2024-02-27 16:25 UTC, viverbungag commented
closed the pull request as this ticket is done